### ISSUE TITLE
Unzip any of the zae files does not work

### ISSUE THREAD

**Issue by whitemilan** [ferrolho/collada-robots-collection#1]
I cannot unzip any of the zae files, not with unzip, nor jar or 7z.  The unzippers insist that it is not a zip archive.

**Comment by ferrolho** [comment]
![gif](https://media.giphy.com/media/w9a8XTLPkXNrWbYX7X/giphy.gif)

You can also try to manually change the file extension and see if that helps whatever extraction utility you are using.

**Comment by whitemilan** [comment]
Thanks a lot. The mere clicking was not the problem, I just downloaded the
single files and did not clone the whole repository... Well, a mistake I
will never make again, thanks for the hint and sorry for wasting your time.
Greetings,
Jan

**Comment by ferrolho** [comment]
> I just downloaded the single files and did not clone the whole repository...

Downloading a single file and extracting it should work too. Anyway, glad you're set!

**Comment by whitemilan** [comment]
I am not well versed in git and github, so I always just rightclick -> Save
link as...
The file that gets downloaded then is the html page of the file in github,
but it saves it with the zae filename ending. Well, still pretty stupid,
when I correctly download the raw everything is find. Thanks a lot
